# Script tạo toàn bộ cấu trúc thư mục và file cho dự án SmartPOS Pro
# Tự động tạo tất cả folder và file từ structure.txt

Write-Host "Bắt đầu tạo cấu trúc dự án SmartPOS Pro..." -ForegroundColor Green

# Tạo thư mục gốc
$rootPath = "smartpos-pro"
if (!(Test-Path $rootPath)) {
    New-Item -ItemType Directory -Path $rootPath -Force | Out-Null
}

# Danh sách tất cả các thư mục cần tạo
$directories = @(
    ".github",
    ".github/workflows",
    ".github/ISSUE_TEMPLATE",
    ".vscode",
    "public",
    "public/icons",
    "public/images",
    "public/images/logo",
    "public/images/hero",
    "public/images/features",
    "public/images/testimonials",
    "public/images/mockups",
    "public/videos",
    "public/sounds",
    "public/fonts",
    "public/fonts/Inter",
    "public/fonts/JetBrainsMono",
    "public/locales",
    "public/locales/en",
    "public/locales/vi",
    "src",
    "src/components",
    "src/components/ui",
    "src/components/ui/base",
    "src/components/ui/forms",
    "src/components/ui/navigation",
    "src/components/ui/layout",
    "src/components/ui/feedback",
    "src/components/ui/charts",
    "src/components/ui/animations",
    "src/components/landing",
    "src/components/landing/hero",
    "src/components/landing/features",
    "src/components/landing/testimonials",
    "src/components/landing/pricing",
    "src/components/landing/about",
    "src/components/landing/contact",
    "src/components/landing/common",
    "src/components/dashboard",
    "src/components/dashboard/overview",
    "src/components/dashboard/widgets",
    "src/components/dashboard/layout",
    "src/components/dashboard/common",
    "src/components/pos",
    "src/components/pos/interface",
    "src/components/pos/cart",
    "src/components/pos/payment",
    "src/components/pos/orders",
    "src/components/pos/receipts",
    "src/components/pos/discounts",
    "src/components/inventory",
    "src/components/inventory/products",
    "src/components/inventory/categories",
    "src/components/inventory/stock",
    "src/components/inventory/suppliers",
    "src/components/inventory/purchase",
    "src/components/inventory/warehouses",
    "src/components/inventory/tracking",
    "src/components/customers",
    "src/components/customers/management",
    "src/components/customers/loyalty",
    "src/components/customers/communication",
    "src/components/customers/feedback",
    "src/components/customers/analytics",
    "src/components/analytics",
    "src/components/analytics/dashboard",
    "src/components/analytics/reports",
    "src/components/analytics/sales",
    "src/components/analytics/financial",
    "src/components/analytics/predictions",
    "src/components/analytics/realtime",
    "src/components/staff",
    "src/components/staff/management",
    "src/components/staff/scheduling",
    "src/components/staff/performance",
    "src/components/staff/communication",
    "src/components/settings",
    "src/components/settings/general",
    "src/components/settings/pos",
    "src/components/settings/inventory",
    "src/components/settings/notifications",
    "src/components/settings/security",
    "src/components/settings/integrations",
    "src/components/settings/advanced",
    "src/components/ai",
    "src/components/ai/assistant",
    "src/components/ai/insights",
    "src/components/ai/automation",
    "src/components/ai/ml",
    "src/components/auth",
    "src/components/auth/login",
    "src/components/auth/register",
    "src/components/auth/recovery",
    "src/components/auth/profile",
    "src/components/auth/guards",
    "src/components/mobile",
    "src/components/mobile/responsive",
    "src/components/mobile/touch",
    "src/components/mobile/offline",
    "src/components/mobile/pwa",
    "src/components/integrations",
    "src/components/integrations/payment",
    "src/components/integrations/shipping",
    "src/components/integrations/accounting",
    "src/components/integrations/marketing",
    "src/components/integrations/ecommerce",
    "src/components/integrations/hardware",
    "src/components/shared",
    "src/components/shared/constants",
    "src/components/shared/hooks",
    "src/components/shared/context",
    "src/components/shared/hoc",
    "src/layouts",
    "src/pages",
    "src/pages/blog",
    "src/pages/blog/category",
    "src/pages/docs",
    "src/pages/docs/api",
    "src/pages/docs/guides",
    "src/pages/docs/tutorials",
    "src/pages/auth",
    "src/pages/dashboard",
    "src/pages/pos",
    "src/pages/pos/orders",
    "src/pages/pos/orders/edit",
    "src/pages/pos/payments",
    "src/pages/pos/receipts",
    "src/pages/pos/receipts/preview",
    "src/pages/pos/discounts",
    "src/pages/pos/discounts/edit",
    "src/pages/inventory",
    "src/pages/inventory/products",
    "src/pages/inventory/products/edit",
    "src/pages/inventory/products/categories",
    "src/pages/inventory/products/variants",
    "src/pages/inventory/products/bundles",
    "src/pages/inventory/stock",
    "src/pages/inventory/suppliers",
    "src/pages/inventory/suppliers/edit",
    "src/pages/inventory/suppliers/orders",
    "src/pages/inventory/suppliers/payments",
    "src/pages/inventory/purchase",
    "src/pages/inventory/purchase/orders",
    "src/pages/inventory/purchase/orders/edit",
    "src/pages/inventory/warehouses",
    "src/pages/inventory/warehouses/edit",
    "src/pages/inventory/warehouses/layout",
    "src/pages/inventory/warehouses/staff",
    "src/pages/inventory/warehouses/zones",
    "src/pages/inventory/warehouses/reports",
    "src/pages/inventory/tracking",
    "src/pages/customers",
    "src/pages/customers/management",
    "src/pages/customers/management/edit",
    "src/pages/customers/management/profile",
    "src/pages/customers/management/history",
    "src/pages/customers/management/orders",
    "src/pages/customers/management/payments",
    "src/pages/customers/management/segments",
    "src/pages/customers/loyalty",
    "src/pages/customers/communication",
    "src/pages/customers/communication/email",
    "src/pages/customers/communication/sms",
    "src/pages/customers/communication/push",
    "src/pages/customers/communication/chat",
    "src/pages/customers/feedback",
    "src/pages/customers/feedback/surveys",
    "src/pages/customers/feedback/forms",
    "src/pages/customers/analytics",
    "src/pages/analytics",
    "src/pages/analytics/dashboard",
    "src/pages/analytics/reports",
    "src/pages/analytics/reports/view",
    "src/pages/analytics/reports/edit",
    "src/pages/analytics/sales",
    "src/pages/analytics/financial",
    "src/pages/analytics/predictions",
    "src/pages/analytics/realtime",
    "src/pages/staff",
    "src/pages/staff/management",
    "src/pages/staff/management/edit",
    "src/pages/staff/management/profile",
    "src/pages/staff/management/roles",
    "src/pages/staff/management/permissions",
    "src/pages/staff/scheduling",
    "src/pages/staff/scheduling/shifts",
    "src/pages/staff/scheduling/shifts/edit",
    "src/pages/staff/scheduling/attendance",
    "src/pages/staff/scheduling/time-tracking",
    "src/pages/staff/scheduling/requests",
    "src/pages/staff/scheduling/payroll",
    "src/pages/staff/performance",
    "src/pages/staff/performance/targets",
    "src/pages/staff/performance/reviews",
    "src/pages/staff/performance/training",
    "src/pages/staff/performance/skills",
    "src/pages/staff/communication",
    "src/pages/staff/communication/chat",
    "src/pages/staff/communication/announcements",
    "src/pages/staff/communication/tasks",
    "src/pages/settings",
    "src/pages/settings/general",
    "src/pages/settings/pos",
    "src/pages/settings/inventory",
    "src/pages/settings/notifications",
    "src/pages/settings/security",
    "src/pages/settings/integrations",
    "src/pages/settings/advanced",
    "src/pages/ai",
    "src/pages/ai/assistant",
    "src/pages/ai/insights",
    "src/pages/ai/automation",
    "src/pages/ai/ml",
    "src/pages/mobile",
    "src/pages/integrations",
    "src/core",
    "src/core/api",
    "src/core/auth",
    "src/core/config",
    "src/core/guards",
    "src/core/interceptors",
    "src/core/services",
    "src/data",
    "src/data/constants",
    "src/data/enums",
    "src/data/interfaces",
    "src/data/mocks",
    "src/data/models",
    "src/helpers",
    "src/hooks",
    "src/routes",
    "src/store",
    "src/utils",
    "docs",
    "scripts",
    "config",
    "tests",
    "tests/unit",
    "tests/integration",
    "tests/e2e",
    "tests/fixtures",
    "tests/mocks",
    "tests/utils"
)

# Tạo tất cả các thư mục
Write-Host "Tạo thư mục..." -ForegroundColor Yellow
foreach ($dir in $directories) {
    $fullPath = Join-Path $rootPath $dir
    if (!(Test-Path $fullPath)) {
        New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
        Write-Host "  ✓ $dir" -ForegroundColor Gray
    }
}

# Danh sách tất cả các file cần tạo
$files = @(
    # GitHub files
    ".github/workflows/ci.yml",
    ".github/workflows/cd.yml",
    ".github/workflows/security.yml",
    ".github/ISSUE_TEMPLATE/bug_report.md",
    ".github/ISSUE_TEMPLATE/feature_request.md",
    ".github/pull_request_template.md",
    
    # VSCode files
    ".vscode/settings.json",
    ".vscode/extensions.json",
    ".vscode/launch.json",
    
    # Public files
    "public/icons/apple-touch-icon.png",
    "public/icons/favicon.ico",
    "public/icons/favicon-16x16.png",
    "public/icons/favicon-32x32.png",
    "public/icons/manifest.json",
    "public/images/logo/logo.svg",
    "public/images/logo/logo-dark.svg",
    "public/images/logo/logo-light.svg",
    "public/images/logo/logo-icon.svg",
    "public/images/hero/hero-bg.jpg",
    "public/images/hero/hero-dashboard.png",
    "public/images/hero/hero-mobile.png",
    "public/images/features/pos-interface.png",
    "public/images/features/analytics-dashboard.png",
    "public/images/features/inventory-management.png",
    "public/images/features/customer-management.png",
    "public/images/testimonials/user-1.jpg",
    "public/images/testimonials/user-2.jpg",
    "public/images/testimonials/user-3.jpg",
    "public/images/mockups/mobile-mockup.png",
    "public/images/mockups/tablet-mockup.png",
    "public/images/mockups/desktop-mockup.png",
    "public/videos/demo-video.mp4",
    "public/videos/tutorial-intro.mp4",
    "public/sounds/notification.mp3",
    "public/sounds/success.mp3",
    "public/sounds/error.mp3",
    "public/fonts/Inter/Inter-Regular.woff2",
    "public/fonts/Inter/Inter-Bold.woff2",
    "public/fonts/Inter/Inter-SemiBold.woff2",
    "public/fonts/JetBrainsMono/JetBrainsMono-Regular.woff2",
    "public/fonts/JetBrainsMono/JetBrainsMono-Bold.woff2",
    "public/locales/en/common.json",
    "public/locales/vi/common.json",
    "public/locales/index.js",
    "public/sw.js",
    "public/robots.txt",
    "public/sitemap.xml",
    
    # UI Base Components
    "src/components/ui/base/Button.astro",
    "src/components/ui/base/Input.astro",
    "src/components/ui/base/Select.astro",
    "src/components/ui/base/Textarea.astro",
    "src/components/ui/base/Checkbox.astro",
    "src/components/ui/base/Radio.astro",
    "src/components/ui/base/Switch.astro",
    "src/components/ui/base/Badge.astro",
    "src/components/ui/base/Avatar.astro",
    "src/components/ui/base/Card.astro",
    "src/components/ui/base/Modal.astro",
    "src/components/ui/base/Dropdown.astro",
    "src/components/ui/base/Tooltip.astro",
    "src/components/ui/base/Loading.astro",
    "src/components/ui/base/Skeleton.astro",
    "src/components/ui/base/Progress.astro",
    "src/components/ui/base/Alert.astro",
    "src/components/ui/base/Toast.astro",
    "src/components/ui/base/Breadcrumb.astro",
    "src/components/ui/base/Pagination.astro",
    "src/components/ui/base/Tabs.astro",
    "src/components/ui/base/Accordion.astro",
    "src/components/ui/base/Table.astro",
    "src/components/ui/base/DataTable.astro",
    "src/components/ui/base/EmptyState.astro",
    "src/components/ui/base/index.ts",
    
    # UI Forms Components
    "src/components/ui/forms/Form.astro",
    "src/components/ui/forms/FormField.astro",
    "src/components/ui/forms/FormError.astro",
    "src/components/ui/forms/FormLabel.astro",
    "src/components/ui/forms/FormGroup.astro",
    "src/components/ui/forms/FormValidation.astro",
    "src/components/ui/forms/ImageUpload.astro",
    "src/components/ui/forms/FileUpload.astro",
    "src/components/ui/forms/DatePicker.astro",
    "src/components/ui/forms/TimePicker.astro",
    "src/components/ui/forms/ColorPicker.astro",
    "src/components/ui/forms/RichTextEditor.astro",
    "src/components/ui/forms/CodeEditor.astro",
    "src/components/ui/forms/SearchInput.astro",
    "src/components/ui/forms/AutoComplete.astro",
    "src/components/ui/forms/TagInput.astro",
    "src/components/ui/forms/NumberInput.astro",
    "src/components/ui/forms/CurrencyInput.astro",
    "src/components/ui/forms/PasswordInput.astro",
    "src/components/ui/forms/index.ts",
    
    # UI Navigation Components
    "src/components/ui/navigation/Navbar.astro",
    "src/components/ui/navigation/Sidebar.astro",
    "src/components/ui/navigation/MobileMenu.astro",
    "src/components/ui/navigation/MenuItems.astro",
    "src/components/ui/navigation/BrandLogo.astro",
    "src/components/ui/navigation/UserMenu.astro",
    "src/components/ui/navigation/NotificationMenu.astro",
    "src/components/ui/navigation/SearchBar.astro",
    "src/components/ui/navigation/ThemeToggle.astro",
    "src/components/ui/navigation/LanguageToggle.astro",
    "src/components/ui/navigation/QuickActions.astro",
    "src/components/ui/navigation/index.ts",
    
    # UI Layout Components
    "src/components/ui/layout/Container.astro",
    "src/components/ui/layout/Grid.astro",
    "src/components/ui/layout/Flex.astro",
    "src/components/ui/layout/Stack.astro",
    "src/components/ui/layout/Spacer.astro",
    "src/components/ui/layout/Divider.astro",
    "src/components/ui/layout/Section.astro",
    "src/components/ui/layout/Header.astro",
    "src/components/ui/layout/Footer.astro",
    "src/components/ui/layout/Aside.astro",
    "src/components/ui/layout/Main.astro",
    "src/components/ui/layout/index.ts",
    
    # UI Feedback Components
    "src/components/ui/feedback/Toast.astro",
    "src/components/ui/feedback/ToastContainer.astro",
    "src/components/ui/feedback/Notification.astro",
    "src/components/ui/feedback/NotificationCenter.astro",
    "src/components/ui/feedback/ConfirmDialog.astro",
    "src/components/ui/feedback/AlertDialog.astro",
    "src/components/ui/feedback/ErrorBoundary.astro",
    "src/components/ui/feedback/SuccessMessage.astro",
    "src/components/ui/feedback/ErrorMessage.astro",
    "src/components/ui/feedback/WarningMessage.astro",
    "src/components/ui/feedback/InfoMessage.astro",
    "src/components/ui/feedback/index.ts",
    
    # UI Charts Components
    "src/components/ui/charts/LineChart.astro",
    "src/components/ui/charts/BarChart.astro",
    "src/components/ui/charts/PieChart.astro",
    "src/components/ui/charts/DoughnutChart.astro",
    "src/components/ui/charts/AreaChart.astro",
    "src/components/ui/charts/RadarChart.astro",
    "src/components/ui/charts/ScatterChart.astro",
    "src/components/ui/charts/HeatmapChart.astro",
    "src/components/ui/charts/GaugeChart.astro",
    "src/components/ui/charts/TreemapChart.astro",
    "src/components/ui/charts/SankeyChart.astro",
    "src/components/ui/charts/ChartContainer.astro",
    "src/components/ui/charts/ChartLegend.astro",
    "src/components/ui/charts/ChartTooltip.astro",
    "src/components/ui/charts/index.ts",
    
    # UI Animations Components
    "src/components/ui/animations/FadeIn.astro",
    "src/components/ui/animations/SlideIn.astro",
    "src/components/ui/animations/ScaleIn.astro",
    "src/components/ui/animations/RotateIn.astro",
    "src/components/ui/animations/BounceIn.astro",
    "src/components/ui/animations/Parallax.astro",
    "src/components/ui/animations/CountUp.astro",
    "src/components/ui/animations/TypeWriter.astro",
    "src/components/ui/animations/Reveal.astro",
    "src/components/ui/animations/Stagger.astro",
    "src/components/ui/animations/Magnetic.astro",
    "src/components/ui/animations/Cursor.astro",
    "src/components/ui/animations/index.ts",
    
    # Landing Components
    "src/components/landing/hero/HeroSection.astro",
    "src/components/landing/hero/HeroContent.astro",
    "src/components/landing/hero/HeroVisual.astro",
    "src/components/landing/hero/HeroStats.astro",
    "src/components/landing/hero/HeroCTA.astro",
    "src/components/landing/hero/HeroVideo.astro",
    "src/components/landing/hero/index.ts",
    "src/components/landing/features/FeaturesSection.astro",
    "src/components/landing/features/FeatureCard.astro",
    "src/components/landing/features/FeatureGrid.astro",
    "src/components/landing/features/FeatureComparison.astro",
    "src/components/landing/features/FeatureDemo.astro",
    "src/components/landing/features/FeatureHighlight.astro",
    "src/components/landing/features/FeatureTimeline.astro",
    "src/components/landing/features/index.ts",
    "src/components/landing/testimonials/TestimonialSection.astro",
    "src/components/landing/testimonials/TestimonialCard.astro",
    "src/components/landing/testimonials/TestimonialCarousel.astro",
    "src/components/landing/testimonials/TestimonialGrid.astro",
    "src/components/landing/testimonials/TestimonialVideo.astro",
    "src/components/landing/testimonials/index.ts",
    "src/components/landing/pricing/PricingSection.astro",
    "src/components/landing/pricing/PricingCard.astro",
    "src/components/landing/pricing/PricingTable.astro",
    "src/components/landing/pricing/PricingComparison.astro",
    "src/components/landing/pricing/PricingFAQ.astro",
    "src/components/landing/pricing/PricingCalculator.astro",
    "src/components/landing/pricing/index.ts",
    "src/components/landing/about/AboutSection.astro",
    "src/components/landing/about/TeamSection.astro",
    "src/components/landing/about/TimelineSection.astro",
    "src/components/landing/about/ValuesSection.astro",
    "src/components/landing/about/StatsSection.astro",
    "src/components/landing/about/index.ts",
    "src/components/landing/contact/ContactSection.astro",
    "src/components/landing/contact/ContactForm.astro",
    "src/components/landing/contact/ContactInfo.astro",
    "src/components/landing/contact/ContactMap.astro",
    "src/components/landing/contact/ContactFAQ.astro",
    "src/components/landing/contact/index.ts",
    "src/components/landing/common/Header.astro",
    "src/components/landing/common/Footer.astro",
    "src/components/landing/common/CTA.astro",
    "src/components/landing/common/Newsletter.astro",
    "src/components/landing/common/Social.astro",
    "src/components/landing/common/BackToTop.astro",
    "src/components/landing/common/index.ts",
    
    # Layouts
    "src/layouts/BaseLayout.astro",
    "src/layouts/LandingLayout.astro",
    "src/layouts/DashboardLayout.astro",
    "src/layouts/AuthLayout.astro",
    "src/layouts/POSLayout.astro",
    "src/layouts/MobileLayout.astro",
    "src/layouts/ErrorLayout.astro",
    "src/layouts/PrintLayout.astro",
    "src/layouts/EmailLayout.astro",
    "src/layouts/index.ts",
    
    # Pages
    "src/pages/index.astro",
    "src/pages/about.astro",
    "src/pages/features.astro",
    "src/pages/pricing.astro",
    "src/pages/contact.astro",
    "src/pages/blog/index.astro",
    "src/pages/blog/[slug].astro",
    "src/pages/blog/category/[category].astro",
    "src/pages/docs/index.astro",
    "src/pages/docs/getting-started.astro",
    "src/pages/docs/api/index.astro",
    "src/pages/docs/api/[endpoint].astro",
    "src/pages/docs/guides/index.astro",
    "src/pages/docs/guides/[guide].astro",
    "src/pages/docs/tutorials/index.astro",
    "src/pages/docs/tutorials/[tutorial].astro",
    "src/pages/auth/login.astro",
    "src/pages/auth/register.astro",
    "src/pages/auth/forgot-password.astro",
    "src/pages/auth/reset-password.astro",
    "src/pages/auth/verify-email.astro",
    "src/pages/auth/two-factor.astro",
    "src/pages/auth/logout.astro",
    "src/pages/dashboard/index.astro",
    "src/pages/dashboard/overview.astro",
    "src/pages/dashboard/quick-start.astro",
    "src/pages/dashboard/notifications.astro",
    "src/pages/dashboard/profile.astro",
    "src/pages/dashboard/settings.astro",
    
    # Core files
    "src/core/api/index.ts",
    "src/core/auth/index.ts",
    "src/core/config/index.ts",
    "src/core/guards/index.ts",
    "src/core/interceptors/index.ts",
    "src/core/services/index.ts",
    
    # Data files
    "src/data/constants/index.ts",
    "src/data/enums/index.ts",
    "src/data/interfaces/index.ts",
    "src/data/mocks/index.ts",
    "src/data/models/index.ts",
    
    # Helper files
    "src/helpers/index.ts",
    "src/hooks/index.ts",
    "src/routes/index.ts",
    "src/store/index.ts",
    "src/utils/index.ts",
    
    # Root files
    "package.json",
    "astro.config.mjs",
    "tsconfig.json",
    "tailwind.config.js",
    "postcss.config.js",
    ".env.example",
    ".env.local",
    ".gitignore",
    ".eslintrc.js",
    ".prettierrc",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    
    # Documentation
    "docs/README.md",
    "docs/INSTALLATION.md",
    "docs/CONFIGURATION.md",
    "docs/API.md",
    "docs/DEPLOYMENT.md",
    "docs/TROUBLESHOOTING.md",
    
    # Scripts
    "scripts/build.js",
    "scripts/dev.js",
    "scripts/test.js",
    "scripts/deploy.js",
    "scripts/setup.js",
    
    # Config
    "config/database.js",
    "config/auth.js",
    "config/mail.js",
    "config/cache.js",
    "config/queue.js",
    
    # Tests
    "tests/unit/example.test.js",
    "tests/integration/example.test.js",
    "tests/e2e/example.test.js",
    "tests/fixtures/data.json",
    "tests/mocks/api.js",
    "tests/utils/helpers.js"
)

# Tạo tất cả các file
Write-Host "Tạo file..." -ForegroundColor Yellow
foreach ($file in $files) {
    $fullPath = Join-Path $rootPath $file
    $directory = Split-Path $fullPath -Parent
    
    # Tạo thư mục nếu chưa tồn tại
    if (!(Test-Path $directory)) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }
    
    # Tạo file rỗng
    if (!(Test-Path $fullPath)) {
        New-Item -ItemType File -Path $fullPath -Force | Out-Null
        Write-Host "  ✓ $file" -ForegroundColor Gray
    }
}

Write-Host "`nHoàn thành! Đã tạo cấu trúc dự án SmartPOS Pro." -ForegroundColor Green
Write-Host "Tổng số thư mục: $($directories.Count)" -ForegroundColor Cyan
Write-Host "Tổng số file: $($files.Count)" -ForegroundColor Cyan
Write-Host "`nCấu trúc dự án đã sẵn sàng để phát triển!" -ForegroundColor Magenta
