name = "computerpos-api"
main = "production-worker.js"
compatibility_date = "2023-11-15"

# D1 Database binding (will be added later)
# [[d1_databases]]
# binding = "DB"
# database_name = "computerpos-production-db"
# database_id = "create-new-database"

[vars]
NODE_ENV = "production"
FRONTEND_URL = "https://pos-frontend-e1q.pages.dev"
LOG_LEVEL = "info"

# Production environment
[env.production]
vars = { NODE_ENV = "production", LOG_LEVEL = "warn" }
