name = "pos-backend"
main = "src/index.js"
compatibility_date = "2024-01-15"

[[ d1_databases ]]
binding = "DB"
database_name = "pos-db"
database_id = "5299f7e8-c458-4db4-9866-124c392a6dd8"

[vars]
ENVIRONMENT = "production"

# For local development
[[env.dev.d1_databases]]
binding = "DB"
database_name = "pos-db-dev"
database_id = "dev-database-id" 