name = "computerpos-api"
account_id = "5b62d10947844251d23e0eac532531dd"
compatibility_date = "2025-07-19"
main = "src/complete-api.js"
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"
workers_dev = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pos-local-db"
database_id = "d42528cd-d0a6-4246-9386-791b9b7506bf"

[env.production]
name = "computerpos-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pos-local-db"
database_id = "d42528cd-d0a6-4246-9386-791b9b7506bf"